### ISSUE TITLE
Angular 16.x support

### ISSUE THREAD

**Issue by ZaidPathan** [btxtiger/ngx-link-preview#39]
@btxtiger Is there any plan for Angular 16 suport?

**Comment by jonaaix** [comment]
@ZaidPathan I haven't used it for a very long time. Should be still compatible to Angular 16. Are you experiencing issues?

**Comment by ZaidPathan** [comment]
@btxtiger Yes, Getting following error as I upgraded from Angular 12.x to 16.x.
<img width="489" alt="image" src="https://github.com/btxtiger/ngx-link-preview/assets/9817196/220a2b70-2607-41cd-8785-e9945b4a6390">

**Comment by jonaaix** [comment]
Ah yes, the Ivy build issue. Should be quickly fixable, I'll check it tomorrow.

**Comment by jonaaix** [comment]
@ZaidPathan Please have a try with version 1.2.0

**Comment by ZaidPathan** [comment]
Worked, Thanks a lot @btxtiger.
