### ISSUE TITLE
Not compatible with Angular 9

### ISSUE THREAD

**Issue by abhishek-thesunflowerlab** [btxtiger/ngx-link-preview#4]
Getting the following message:

This likely means that the library (ngx-link-preview) which declares NgxLinkPreviewModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also, consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

@btxtiger

**Comment by jonaaix** [comment]
@abhishek-thesunflowerlab Are you sure that you have the latest version installed? If you are using yarn, you might get a package from a lower version in range. You can check the installed version in `node_modules/ngx-link-preview/package.json`.
I have recompiled the modules just a few months ago 🤔

**Comment by abhishek-thesunflowerlab** [comment]
@btxtiger yes, it working now. Thank you
