### ISSUE TITLE
issues with angular 13 version

### ISSUE THREAD

**Issue by erkishanvaishnani** [btxtiger/ngx-link-preview#41]
I am getting error in angular 13 project 

![image](https://github.com/btxtiger/ngx-link-preview/assets/33306886/e45b6a53-b423-4c5c-9216-34a9ea47da21)

**Comment by jonaaix** [comment]
Ich did some updates last month, to match the latest Angular requirements (Angular 14+). For Angular 13 you should go with version 1.1.7

**Comment by erkishanvaishnani** [comment]
It works thanks.
