### ISSUE TITLE
render link from an input

### ISSUE THREAD

**Issue by anouar1991** [btxtiger/ngx-link-preview#6]
Good day ! 
I'm using this extension and  I like it so far, I faced some issues using it such as rendering links from an input element. let me explain with an example:
I have a URL input
`` 
<input type="url" #url/>
   
 <ng-container *ngIf="isUrl(url.value)">

<ngx-link-preview
      [apiRoute]="'http://v2node.local/api/link-preview/test'"
      [getApiEndpoint$]="apiCallbackFn"
      [parseForLinksStr]="url.value"
      [queryParamName]="'url'"
    ></ngx-link-preview>
</ng-container>
``
in this use case, the extension keeps sending requests on every found URL if le's say I wanted to get metadata for https://www.google.com I will be getting a list of  previews for these links ( if they exist )  : 
https://www.g.com
https://www.go.com
https://www.goo.com
https://www.goog.com
https://www.googl.com
https://www.google.com

![image](https://user-images.githubusercontent.com/16974390/87256336-6eff2500-c489-11ea-90c8-0fe0e1f886a4.png)

It would be nice if there is an option for fetching only one link ( the last link for example). and make the *fetching list of links* optional

**Comment by jonaaix** [comment]
The links should be usually cleared on change (if I understood your issue correctly) 🤔
You can alternatively try using `[links]="[url.value]"`, until I get a chance to check it tomorrow.

**Comment by vipul306** [comment]
I tried to use ngx-link-preview. 

I am using Angular 9 

Once installed successfully, when I compiled it gives below error. 

**ERROR**
Method not implemented.
    at AstTranslator.visitQuote (D:\GitHub\VS05_JUL_2021\Frontend\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:212:69)


Let me know if I am missing anything or any specific requirement to use this tag. 


Thanks

**Comment by jonaaix** [comment]
@vipul306 is there the missing backslash in the error message? `nd\node_modules@angular\co`
